name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Format
      run: cargo fmt --all-targets
    - name: Build
      run: cargo build --verbose --all-targets
    - name: Clippy
      run: cargo clippy --all-targets
    - name: Run tests
      run: cargo test --verbose
